/// <reference types="nativewind/types" />


declare module "*.png";
declare module "*.svg";
declare module "*.jpeg";
declare module "*.jpg";
// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.